### ISSUE TITLE
DEPEŠE: Chceme zavést malé a velké depeše.

### ISSUE THREAD

**Issue by davidvavra** [davidvavra/dune-new-dawn#2]
Ve velké depeši má hráč akci s každou armádou/špionem/hrdinou plus 1 akci na mise.

V malé depeši má hráč jednu akci "libovolnou" a jednu na mise. 

Imo je to podporované již v současné implementaci, jen potřebujeme asi nový typ akce "libovolná".

**Comment by davidvavra** [comment]
Tohle moc nechápu, znamená to že nějaká kola budou menší a některá větší? Pokud implementujeme #3 , tak to půjde nastavit - prostě v menším kole nastavíš 0 armádních akcí atd.

Takže jde jenom o přidání typu akce "libovolná"? Je wording finální?

@HannibalCZ

**Comment by HannibalCZ** [comment]
Jj, budeme střídat malá a větší kola. Chceme totiž během hracího večera odehrát dvě kola, ale plnohodnotné kolo bychom nestihli vyhodnotit. Takže v první třetině session hráči odešlou "malou depeši", kterou rychle vyhodnotíme zatímco hráči budou jednat na Landsraadu. Na konci session pak pošlou "velkou depeši", kde bude akcí víc a ty vyhodnotíme v klidu druhý den.

Souhlasím, že když implementujeme ten druhý ticket, tak je to o přidání dalšího typu akce (např. "libovolná") a pak už by to mělo jít nastavit v appce tak, že něčemu dáš 0 a něčemu více.

Wording bohužel ještě finální není, takže s dotáhnutím tohohle ticketu zatím počkejme. Beztak je závislí na tom druhém.

**Comment by davidvavra** [comment]
Tuhle issue zavírám, vyřeší se implementací #3
